spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  hibernate:
    ddl-auto: create

servlet:
  port: 8081
  context-path: /data
