server:
  port: 8180

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8183"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: hardcore-service
          uri: http://localhost:8181
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-core/api/v1
            - JwtAuthFilter
        - id: cart-service
          uri: http://localhost:8182
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-carts/api/v1
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8185
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-auth/api/v1
            - JwtAuthFilter

jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g

#logging:
#  level:
#    reactor:
#      netty: TRACE
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE
