server:
  port: 8188

#logging:
#  level:
#    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8183"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
      routes:
        - id: core-service
          uri: http://localhost:8181
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-core
            - JwtAuthFilter
        - id: cart-service
          uri: http://localhost:8182
          predicates:
            - Path=/carts/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-carts
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8185
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-auth
            - JwtAuthFilter

jwt:
  secret: adfkjasbflkjahgkj;ahglkjagbljkadfgbakjghajkfahfagag


#logging:
#  level:
#    reactor:
#      netty: TRACE
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE
