server:
  port: 8180

logging:
  level:
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:8183"
#            allowedHeaders: "*"
#            allowedMethods:
#              - GET
#              - POST
      routes:
        - id: hardcore-service
          uri: http://localhost:8181
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-core/api/v1
            - JwtAuthFilter
        - id: cart-service
          uri: http://localhost:8182
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-carts/api/v1
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8185
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-auth/api/v1
            - JwtAuthFilter

jwt:
  secret: adfkjasbflkjahgkj;ahglkjagbljkadfgbakjghajkfahfagag

#logging:
#  level:
#    reactor:
#      netty: TRACE
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE
