spring:
  flyway:
    locations: classpath:/db/testdata
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_secure_db
    username: postgres
    password: kolbaska
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect