
server:
  port: 8182
  servlet:
      context-path: /market-carts

integrations:
  product-service:
    url: http://localhost:8181/market-core
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000
cart-service:
  cart-prefix: winter_cart_